# Generated by Django 3.1.7 on 2022-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Коммент')),
                ('created', models.DateTimeField(verbose_name='Сохранён')),
                ('id_user', models.EmailField(max_length=254, verbose_name='Почта')),
                ('image_characteristics', models.TextField(verbose_name='Характеристики изображения')),
                ('result_network', models.TextField(verbose_name='Результат от нейронной сети')),
                ('result_expert_system', models.TextField(verbose_name='Результат от экспертной системы')),
                ('img_uri', models.TextField(verbose_name='Ссылка на изображение'))
            ],
        ),
    ]
